// These values must match the com.konami.jcef.MessageRouterHandler.java constants
export const CONNECT = 'connect'
export const GET_CAMERA_IMAGE_PREVIEW = 'getCameraImagePreview'
export const GET_SCANNER_IMAGE_PREVIEW = 'getScannerImagePreview'
export const GET_FILE_IMAGE_PREVIEW = 'getFileImagePreview'
export const GET_FOLLOWING_ID = 'getFollowingID'
export const GET_GAMESITE = 'getGamesite'
export const GET_IOP = 'getIOP'
export const GET_KONAMI_WEB_URI = 'getKonamiWebURI'
export const GET_SESSION = 'getSession'
export const IS_CAMERA_AVAILABLE = 'isCameraAvailable'
export const IS_SCANNER_AVAILABLE = 'isScannerAvailable'
export const JAVASCRIPT_READY = 'javascriptReady'
export const LOAD_MENU_ITEM_BY_IDS = 'loadMenuItemByIds'
export const PAGE_INIT = 'pageInit'
export const PAGE_READY = 'pageReady'
export const SET_FOLLOWING_ID = 'setFollowingID'
export const SET_SESSION = 'setSession'
// Old window.menuio commands
export const CHANGE_PASSWORD = 'changePassword'
export const EXIT_SYNKROS = 'exitSynkros'
export const LOG_OFF_SYNKROS = 'logOffSynkros'
// Old window.java commands
export const CLEAR_FOLLOWING_ID = 'clearFollowingID'
export const GET_AND_SAVE_PATRON_IMAGE = 'getAndSavePatronImage'
export const GET_FILE = 'getFile'
export const GET_SERVER_RESPONSE_MESSAGE = 'getServerResponseMessage'
export const GET_SHARED_PUBLIC_KEY = 'getSharedPublicKey'
export const GET_SHARED_SECURE_KEY = 'getSharedSecureKey'
export const LOG_MESSAGE_TO_SYNKROS = 'logMessageToSynkros'
export const PRINT_CARD = 'printCard'
export const PRINT_SERVER_FILE = 'printServerFile'
export const SAVE_CSV_FILE = 'saveCSVFile'
export const SET_SHARED_PUBLIC_KEY = 'setSharedPublicKey'
export const SET_SHARED_SECURE_KEY = 'setSharedSecureKey'
export const STORE_PATRON_IMAGES_BY_PTNID = 'storePatronImagesByPtnid'
// bridge receiver actions
export const RECEIVE_JAVA_IMAGE = 'RECEIVE_JAVA_IMAGE'
export const SET_KEY_EXCHANGE_HEADER_VAL = 'setKeyExchangeHeaderVal'
